datos_aperturas={
    "A00": "Aperturas Irregulares",
    "A01": "Apertura Nimzowitsch",
    "A02": "Apertura Bird",
    "A03": "Apertura Bird",
    "A04": "Apertura Réti",
    "A05": "Apertura Réti",
    "A06": "Apertura Réti",
    "A07": "Apertura Réti",
    "A08": "Apertura Réti",
    "A09": "Apertura Réti",
    "A10": "Apertura Inglesa",
    "A11": "Apertura Inglesa",
    "A12": "Apertura Inglesa",
    "A13": "Apertura Inglesa",
    "A14": "Apertura Inglesa",
    "A15": "Apertura Inglesa",
    "A16": "Apertura Inglesa",
    "A17": "Apertura Inglesa",
    "A18": "Apertura Inglesa",
    "A19": "Apertura Inglesa",
    "A20": "Apertura Inglesa",
    "A21": "Apertura Inglesa",
    "A22": "Apertura Inglesa",
    "A23": "Apertura Inglesa",
    "A24": "Apertura Inglesa",
    "A25": "Apertura Inglesa",
    "A26": "Apertura Inglesa",
    "A27": "Apertura Inglesa",
    "A28": "Apertura Inglesa",
    "A29": "Apertura Inglesa",
    "A30": "Apertura Inglesa",
    "A31": "Apertura Inglesa",
    "A32": "Apertura Inglesa",
    "A33": "Apertura Inglesa",
    "A34": "Apertura Inglesa",
    "A35": "Apertura Inglesa",
    "A36": "Apertura Inglesa",
    "A37": "Apertura Inglesa",
    "A38": "Apertura Inglesa",
    "A39": "Apertura Inglesa",
    "A40": "Peón de Dama Irregular",
    "A41": "Defensa Moderna",
    "A42": "Defensa Moderna",
    "A43": "Benoni Antigua",
    "A44": "Benoni Antigua",
    "A45": "Defensas Indias",
    "A46": "Defensas Indias",
    "A47": "Defensas Indias",
    "A48": "Defensas Indias",
    "A49": "Defensas Indias",
    "A50": "Defensas Indias",
    "A51": "Gambito Budapest",
    "A52": "Gambito Budapest",
    "A53": "Defensa India Antigua",
    "A54": "Defensa India Antigua",
    "A55": "Defensa India Antigua",
    "A56": "Defensa Benoni",
    "A57": "Gambito Benko",
    "A58": "Gambito Benko",
    "A59": "Gambito Benko",
    "A60": "Benoni Moderna",
    "A61": "Benoni Moderna",
    "A62": "Benoni Moderna",
    "A63": "Benoni Moderna",
    "A64": "Benoni Moderna",
    "A65": "Benoni Moderna",
    "A66": "Benoni Moderna",
    "A67": "Benoni Moderna",
    "A68": "Benoni Moderna",
    "A69": "Benoni Moderna",
    "A70": "Benoni Moderna",
    "A71": "Benoni Moderna",
    "A72": "Benoni Moderna",
    "A73": "Benoni Moderna",
    "A74": "Benoni Moderna",
    "A75": "Benoni Moderna",
    "A76": "Benoni Moderna",
    "A77": "Benoni Moderna",
    "A78": "Benoni Moderna",
    "A79": "Benoni Moderna",
    "A80": "Defensa Holandesa",
    "A81": "Defensa Holandesa",
    "A82": "Defensa Holandesa",
    "A83": "Defensa Holandesa",
    "A84": "Defensa Holandesa",
    "A85": "Defensa Holandesa",
    "A86": "Defensa Holandesa",
    "A87": "Defensa Holandesa",
    "A88": "Defensa Holandesa",
    "A89": "Defensa Holandesa",
    "A90": "Defensa Holandesa",
    "A91": "Defensa Holandesa",
    "A92": "Defensa Holandesa",
    "A93": "Defensa Holandesa",
    "A94": "Defensa Holandesa",
    "A95": "Defensa Holandesa",
    "A96": "Defensa Holandesa",
    "A97": "Defensa Holandesa",
    "A98": "Defensa Holandesa",
    "A99": "Defensa Holandesa",
    "B00": "Peón de Rey Irregular",
    "B01": "Defensa Escandinava",
    "B02": "Defensa Alekhine",
    "B03": "Defensa Alekhine",
    "B04": "Defensa Alekhine",
    "B05": "Defensa Alekhine",
    "B06": "Defensa Robatsch (Moderna)",
    "B07": "Defensa Pirc",
    "B08": "Defensa Pirc",
    "B09": "Defensa Pirc",
    "B10": "Defensa Caro-Kann",
    "B11": "Defensa Caro-Kann",
    "B12": "Defensa Caro-Kann",
    "B13": "Defensa Caro-Kann",
    "B14": "Defensa Caro-Kann",
    "B15": "Defensa Caro-Kann",
    "B16": "Defensa Caro-Kann",
    "B17": "Defensa Caro-Kann",
    "B18": "Defensa Caro-Kann",
    "B19": "Defensa Caro-Kann",
    "B20": "Defensa Siciliana (Parte 1)",
    "B21": "Defensa Siciliana (Parte 1)",
    "B22": "Defensa Siciliana (Parte 1)",
    "B23": "Defensa Siciliana (Parte 1)",
    "B24": "Defensa Siciliana (Parte 1)",
    "B25": "Defensa Siciliana (Parte 1)",
    "B26": "Defensa Siciliana (Parte 1)",
    "B27": "Defensa Siciliana (Parte 1)",
    "B28": "Defensa Siciliana (Parte 1)",
    "B29": "Defensa Siciliana (Parte 1)",
    "B30": "Defensa Siciliana (Parte 1)",
    "B31": "Defensa Siciliana (Parte 1)",
    "B32": "Defensa Siciliana (Parte 1)",
    "B33": "Defensa Siciliana (Parte 1)",
    "B34": "Defensa Siciliana (Parte 1)",
    "B35": "Defensa Siciliana (Parte 1)",
    "B36": "Defensa Siciliana (Parte 1)",
    "B37": "Defensa Siciliana (Parte 1)",
    "B38": "Defensa Siciliana (Parte 1)",
    "B39": "Defensa Siciliana (Parte 1)",
    "B40": "Defensa Siciliana (Parte 1)",
    "B41": "Defensa Siciliana (Parte 1)",
    "B42": "Defensa Siciliana (Parte 1)",
    "B43": "Defensa Siciliana (Parte 1)",
    "B44": "Defensa Siciliana (Parte 1)",
    "B45": "Defensa Siciliana (Parte 1)",
    "B46": "Defensa Siciliana (Parte 1)",
    "B47": "Defensa Siciliana (Parte 1)",
    "B48": "Defensa Siciliana (Parte 1)",
    "B49": "Defensa Siciliana (Parte 1)",
    "B50": "Defensa Siciliana (Parte 1)",
    "B51": "Defensa Siciliana (Parte 1)",
    "B52": "Defensa Siciliana (Parte 1)",
    "B53": "Defensa Siciliana (Parte 1)",
    "B54": "Defensa Siciliana (Parte 1)",
    "B55": "Defensa Siciliana (Parte 1)",
    "B56": "Defensa Siciliana (Parte 1)",
    "B57": "Defensa Siciliana (Parte 1)",
    "B58": "Defensa Siciliana (Parte 1)",
    "B59": "Defensa Siciliana (Parte 1)",
    "B60": "Defensa Siciliana (Parte 2)",
    "B61": "Defensa Siciliana (Parte 2)",
    "B62": "Defensa Siciliana (Parte 2)",
    "B63": "Defensa Siciliana (Parte 2)",
    "B64": "Defensa Siciliana (Parte 2)",
    "B65": "Defensa Siciliana (Parte 2)",
    "B66": "Defensa Siciliana (Parte 2)",
    "B67": "Defensa Siciliana (Parte 2)",
    "B68": "Defensa Siciliana (Parte 2)",
    "B69": "Defensa Siciliana (Parte 2)",
    "B70": "Defensa Siciliana (Parte 2)",
    "B71": "Defensa Siciliana (Parte 2)",
    "B72": "Defensa Siciliana (Parte 2)",
    "B73": "Defensa Siciliana (Parte 2)",
    "B74": "Defensa Siciliana (Parte 2)",
    "B75": "Defensa Siciliana (Parte 2)",
    "B76": "Defensa Siciliana (Parte 2)",
    "B77": "Defensa Siciliana (Parte 2)",
    "B78": "Defensa Siciliana (Parte 2)",
    "B79": "Defensa Siciliana (Parte 2)",
    "B80": "Defensa Siciliana (Parte 2)",
    "B81": "Defensa Siciliana (Parte 2)",
    "B82": "Defensa Siciliana (Parte 2)",
    "B83": "Defensa Siciliana (Parte 2)",
    "B84": "Defensa Siciliana (Parte 2)",
    "B85": "Defensa Siciliana (Parte 2)",
    "B86": "Defensa Siciliana (Parte 2)",
    "B87": "Defensa Siciliana (Parte 2)",
    "B88": "Defensa Siciliana (Parte 2)",
    "B89": "Defensa Siciliana (Parte 2)",
    "B90": "Defensa Siciliana (Parte 2)",
    "B91": "Defensa Siciliana (Parte 2)",
    "B92": "Defensa Siciliana (Parte 2)",
    "B93": "Defensa Siciliana (Parte 2)",
    "B94": "Defensa Siciliana (Parte 2)",
    "B95": "Defensa Siciliana (Parte 2)",
    "B96": "Defensa Siciliana (Parte 2)",
    "B97": "Defensa Siciliana (Parte 2)",
    "B98": "Defensa Siciliana (Parte 2)",
    "B99": "Defensa Siciliana (Parte 2)",
    "C00": "Defensa Francesa",
    "C01": "Defensa Francesa",
    "C02": "Defensa Francesa",
    "C03": "Defensa Francesa",
    "C04": "Defensa Francesa",
    "C05": "Defensa Francesa",
    "C06": "Defensa Francesa",
    "C07": "Defensa Francesa",
    "C08": "Defensa Francesa",
    "C09": "Defensa Francesa",
    "C10": "Defensa Francesa",
    "C11": "Defensa Francesa",
    "C12": "Defensa Francesa",
    "C13": "Defensa Francesa",
    "C14": "Defensa Francesa",
    "C15": "Defensa Francesa",
    "C16": "Defensa Francesa",
    "C17": "Defensa Francesa",
    "C18": "Defensa Francesa",
    "C19": "Defensa Francesa",
    "C20": "Apertura de Peón de Rey",
    "C21": "Apertura del Centro",
    "C22": "Apertura del Centro",
    "C23": "Apertura del Alfil",
    "C24": "Apertura del Alfil",
    "C25": "Apertura Vienesa",
    "C26": "Apertura Vienesa",
    "C27": "Apertura Vienesa",
    "C28": "Apertura Vienesa",
    "C29": "Gambito Vienés",
    "C30": "Gambito de Rey Rehusado",
    "C31": "Contragambito Falkbeer",
    "C32": "Contragambito Falkbeer",
    "C33": "Gambito de Rey Aceptado",
    "C34": "Gambito de Rey Aceptado",
    "C35": "Gambito de Rey Aceptado",
    "C36": "Gambito de Rey Aceptado",
    "C37": "Gambito de Rey Aceptado",
    "C38": "Gambito de Rey Aceptado",
    "C39": "Gambito de Rey Aceptado",
    "C40": "Apertura de Caballo de Rey",
    "C41": "Defensa Philidor",
    "C42": "Defensa Petrov",
    "C43": "Defensa Petrov",
    "C44": "Ponziani / Escocesa",
    "C45": "Apertura Escocesa",
    "C46": "Apertura de los Tres Caballos",
    "C47": "Apertura de los Cuatro Caballos",
    "C48": "Apertura de los Cuatro Caballos",
    "C49": "Apertura de los Cuatro Caballos",
    "C50": "Apertura Italiana",
    "C51": "Gambito Evans",
    "C52": "Gambito Evans",
    "C53": "Giuoco Piano",
    "C54": "Giuoco Piano",
    "C55": "Defensa de los Dos Caballos",
    "C56": "Defensa de los Dos Caballos",
    "C57": "Defensa de los Dos Caballos",
    "C58": "Defensa de los Dos Caballos",
    "C59": "Defensa de los Dos Caballos",
    "C60": "Apertura Española (Ruy López)",
    "C61": "Apertura Española (Ruy López)",
    "C62": "Apertura Española (Ruy López)",
    "C63": "Apertura Española (Ruy López)",
    "C64": "Apertura Española (Ruy López)",
    "C65": "Apertura Española (Ruy López)",
    "C66": "Apertura Española (Ruy López)",
    "C67": "Apertura Española (Ruy López)",
    "C68": "Apertura Española (Ruy López)",
    "C69": "Apertura Española (Ruy López)",
    "C70": "Apertura Española (Ruy López)",
    "C71": "Apertura Española (Ruy López)",
    "C72": "Apertura Española (Ruy López)",
    "C73": "Apertura Española (Ruy López)",
    "C74": "Apertura Española (Ruy López)",
    "C75": "Apertura Española (Ruy López)",
    "C76": "Apertura Española (Ruy López)",
    "C77": "Apertura Española (Ruy López)",
    "C78": "Apertura Española (Ruy López)",
    "C79": "Apertura Española (Ruy López)",
    "C80": "Apertura Española (Ruy López)",
    "C81": "Apertura Española (Ruy López)",
    "C82": "Apertura Española (Ruy López)",
    "C83": "Apertura Española (Ruy López)",
    "C84": "Apertura Española (Ruy López)",
    "C85": "Apertura Española (Ruy López)",
    "C86": "Apertura Española (Ruy López)",
    "C87": "Apertura Española (Ruy López)",
    "C88": "Apertura Española (Ruy López)",
    "C89": "Apertura Española (Ruy López)",
    "C90": "Apertura Española (Ruy López)",
    "C91": "Apertura Española (Ruy López)",
    "C92": "Apertura Española (Ruy López)",
    "C93": "Apertura Española (Ruy López)",
    "C94": "Apertura Española (Ruy López)",
    "C95": "Apertura Española (Ruy López)",
    "C96": "Apertura Española (Ruy López)",
    "C97": "Apertura Española (Ruy López)",
    "C98": "Apertura Española (Ruy López)",
    "C99": "Apertura Española (Ruy López)",
    "D00": "Apertura de Peón de Dama",
    "D01": "Apertura de Peón de Dama",
    "D02": "Apertura de Peón de Dama",
    "D03": "Apertura de Peón de Dama",
    "D04": "Apertura de Peón de Dama",
    "D05": "Apertura de Peón de Dama",
    "D06": "Gambito de Dama",
    "D07": "Gambito de Dama",
    "D08": "Gambito de Dama",
    "D09": "Gambito de Dama",
    "D10": "Defensa Eslava",
    "D11": "Defensa Eslava",
    "D12": "Defensa Eslava",
    "D13": "Defensa Eslava",
    "D14": "Defensa Eslava",
    "D15": "Defensa Eslava",
    "D16": "Defensa Eslava",
    "D17": "Defensa Eslava",
    "D18": "Defensa Eslava",
    "D19": "Defensa Eslava",
    "D20": "Gambito de Dama Aceptado",
    "D21": "Gambito de Dama Aceptado",
    "D22": "Gambito de Dama Aceptado",
    "D23": "Gambito de Dama Aceptado",
    "D24": "Gambito de Dama Aceptado",
    "D25": "Gambito de Dama Aceptado",
    "D26": "Gambito de Dama Aceptado",
    "D27": "Gambito de Dama Aceptado",
    "D28": "Gambito de Dama Aceptado",
    "D29": "Gambito de Dama Aceptado",
    "D30": "Gambito de Dama Rehusado",
    "D31": "Gambito de Dama Rehusado",
    "D32": "Gambito de Dama Rehusado",
    "D33": "Gambito de Dama Rehusado",
    "D34": "Gambito de Dama Rehusado",
    "D35": "Gambito de Dama Rehusado",
    "D36": "Gambito de Dama Rehusado",
    "D37": "Gambito de Dama Rehusado",
    "D38": "Gambito de Dama Rehusado",
    "D39": "Gambito de Dama Rehusado",
    "D40": "Gambito de Dama Rehusado",
    "D41": "Gambito de Dama Rehusado",
    "D42": "Gambito de Dama Rehusado",
    "D43": "Gambito de Dama Rehusado",
    "D44": "Gambito de Dama Rehusado",
    "D45": "Gambito de Dama Rehusado",
    "D46": "Gambito de Dama Rehusado",
    "D47": "Gambito de Dama Rehusado",
    "D48": "Gambito de Dama Rehusado",
    "D49": "Gambito de Dama Rehusado",
    "D50": "Gambito de Dama Rehusado",
    "D51": "Gambito de Dama Rehusado",
    "D52": "Gambito de Dama Rehusado",
    "D53": "Gambito de Dama Rehusado",
    "D54": "Gambito de Dama Rehusado",
    "D55": "Gambito de Dama Rehusado",
    "D56": "Gambito de Dama Rehusado",
    "D57": "Gambito de Dama Rehusado",
    "D58": "Gambito de Dama Rehusado",
    "D59": "Gambito de Dama Rehusado",
    "D60": "Gambito de Dama Rehusado",
    "D61": "Gambito de Dama Rehusado",
    "D62": "Gambito de Dama Rehusado",
    "D63": "Gambito de Dama Rehusado",
    "D64": "Gambito de Dama Rehusado",
    "D65": "Gambito de Dama Rehusado",
    "D66": "Gambito de Dama Rehusado",
    "D67": "Gambito de Dama Rehusado",
    "D68": "Gambito de Dama Rehusado",
    "D69": "Gambito de Dama Rehusado",
    "D70": "Defensa Grünfeld",
    "D71": "Defensa Grünfeld",
    "D72": "Defensa Grünfeld",
    "D73": "Defensa Grünfeld",
    "D74": "Defensa Grünfeld",
    "D75": "Defensa Grünfeld",
    "D76": "Defensa Grünfeld",
    "D77": "Defensa Grünfeld",
    "D78": "Defensa Grünfeld",
    "D79": "Defensa Grünfeld",
    "D80": "Defensa Grünfeld",
    "D81": "Defensa Grünfeld",
    "D82": "Defensa Grünfeld",
    "D83": "Defensa Grünfeld",
    "D84": "Defensa Grünfeld",
    "D85": "Defensa Grünfeld",
    "D86": "Defensa Grünfeld",
    "D87": "Defensa Grünfeld",
    "D88": "Defensa Grünfeld",
    "D89": "Defensa Grünfeld",
    "D90": "Defensa Grünfeld",
    "D91": "Defensa Grünfeld",
    "D92": "Defensa Grünfeld",
    "D93": "Defensa Grünfeld",
    "D94": "Defensa Grünfeld",
    "D95": "Defensa Grünfeld",
    "D96": "Defensa Grünfeld",
    "D97": "Defensa Grünfeld",
    "D98": "Defensa Grünfeld",
    "D99": "Defensa Grünfeld",
    "E00": "Apertura Catalana",
    "E01": "Apertura Catalana",
    "E02": "Apertura Catalana",
    "E03": "Apertura Catalana",
    "E04": "Apertura Catalana",
    "E05": "Apertura Catalana",
    "E06": "Apertura Catalana",
    "E07": "Apertura Catalana",
    "E08": "Apertura Catalana",
    "E09": "Apertura Catalana",
    "E10": "Indias Irregulares",
    "E11": "Defensa Bogo-India",
    "E12": "Defensa India de Dama",
    "E13": "Defensa India de Dama",
    "E14": "Defensa India de Dama",
    "E15": "Defensa India de Dama",
    "E16": "Defensa India de Dama",
    "E17": "Defensa India de Dama",
    "E18": "Defensa India de Dama",
    "E19": "Defensa India de Dama",
    "E20": "Defensa Nimzo-India",
    "E21": "Defensa Nimzo-India",
    "E22": "Defensa Nimzo-India",
    "E23": "Defensa Nimzo-India",
    "E24": "Defensa Nimzo-India",
    "E25": "Defensa Nimzo-India",
    "E26": "Defensa Nimzo-India",
    "E27": "Defensa Nimzo-India",
    "E28": "Defensa Nimzo-India",
    "E29": "Defensa Nimzo-India",
    "E30": "Defensa Nimzo-India",
    "E31": "Defensa Nimzo-India",
    "E32": "Defensa Nimzo-India",
    "E33": "Defensa Nimzo-India",
    "E34": "Defensa Nimzo-India",
    "E35": "Defensa Nimzo-India",
    "E36": "Defensa Nimzo-India",
    "E37": "Defensa Nimzo-India",
    "E38": "Defensa Nimzo-India",
    "E39": "Defensa Nimzo-India",
    "E40": "Defensa Nimzo-India",
    "E41": "Defensa Nimzo-India",
    "E42": "Defensa Nimzo-India",
    "E43": "Defensa Nimzo-India",
    "E44": "Defensa Nimzo-India",
    "E45": "Defensa Nimzo-India",
    "E46": "Defensa Nimzo-India",
    "E47": "Defensa Nimzo-India",
    "E48": "Defensa Nimzo-India",
    "E49": "Defensa Nimzo-India",
    "E50": "Defensa Nimzo-India",
    "E51": "Defensa Nimzo-India",
    "E52": "Defensa Nimzo-India",
    "E53": "Defensa Nimzo-India",
    "E54": "Defensa Nimzo-India",
    "E55": "Defensa Nimzo-India",
    "E56": "Defensa Nimzo-India",
    "E57": "Defensa Nimzo-India",
    "E58": "Defensa Nimzo-India",
    "E59": "Defensa Nimzo-India",
    "E60": "Defensa India de Rey",
    "E61": "Defensa India de Rey",
    "E62": "Defensa India de Rey",
    "E63": "Defensa India de Rey",
    "E64": "Defensa India de Rey",
    "E65": "Defensa India de Rey",
    "E66": "Defensa India de Rey",
    "E67": "Defensa India de Rey",
    "E68": "Defensa India de Rey",
    "E69": "Defensa India de Rey",
    "E70": "Defensa India de Rey",
    "E71": "Defensa India de Rey",
    "E72": "Defensa India de Rey",
    "E73": "Defensa India de Rey",
    "E74": "Defensa India de Rey",
    "E75": "Defensa India de Rey",
    "E76": "Defensa India de Rey",
    "E77": "Defensa India de Rey",
    "E78": "Defensa India de Rey",
    "E79": "Defensa India de Rey",
    "E80": "Defensa India de Rey",
    "E81": "Defensa India de Rey",
    "E82": "Defensa India de Rey",
    "E83": "Defensa India de Rey",
    "E84": "Defensa India de Rey",
    "E85": "Defensa India de Rey",
    "E86": "Defensa India de Rey",
    "E87": "Defensa India de Rey",
    "E88": "Defensa India de Rey",
    "E89": "Defensa India de Rey",
    "E90": "Defensa India de Rey",
    "E91": "Defensa India de Rey",
    "E92": "Defensa India de Rey",
    "E93": "Defensa India de Rey",
    "E94": "Defensa India de Rey",
    "E95": "Defensa India de Rey",
    "E96": "Defensa India de Rey",
    "E97": "Defensa India de Rey",
    "E98": "Defensa India de Rey",
    "E99": "Defensa India de Rey"
}